//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingCar3.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tOrderDetail = new HashSet<tOrderDetail>();
        }

        public int fId { get; set; }

        [DisplayName("訂單編號")]
        public string fOrderGuid { get; set; }

        [DisplayName("會員帳號")]
        public string fUserId { get; set; }

        [DisplayName("收件人姓名")]
        [Required]
        public string fReceiver { get; set; }

        [DisplayName("收件人信箱")]
        [Required]
        [EmailAddress]
        public string fEmail { get; set; }

        [DisplayName("收件人地址")]
        [Required]
        public string fAddress { get; set; }

        [DisplayName("訂單日期")]
        public Nullable<System.DateTime> fDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetail> tOrderDetail { get; set; }
    }
}

