//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingCar3.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;


    public partial class tProduct
    {
        public int fId { get; set; }

        [DisplayName("產品編號")]
        public string fPId { get; set; }

        [DisplayName("品名")]
        public string fName { get; set; }

        [DisplayName("單價")]
        public Nullable<int> fPrice { get; set; }

        [DisplayName("圖示")]
        public string fImg { get; set; }

        [DisplayName("產品說明")]
        public string fContent { get; set; }

        [DisplayName("庫存")]
        public Nullable<int> fQuantity { get; set; }
    }
}
